### ISSUE TITLE
SPT Docker mod loading issue

### ISSUE THREAD

**Issue by novakin** [jbs4bmx/Olympus#1]
Hello,

Great mod, would like to use it on a new config, using docker for spt and here is the error I get when starting the server 

```
Error: ENOENT: no such file or directory, scandir 'user/mods/./database/'
Error: ENOENT: no such file or directory, scandir 'user/mods/./database/'
    at Object.readdirSync (node:fs:1515:26)
    at Object.readdirSync (pkg/prelude/bootstrap.js:1306:35)
    at VFS.getFiles (/snapshot/src/utils/VFS.ts:219:19)
    at ImporterUtil.loadRecursive (/snapshot/src/utils/ImporterUtil.ts:87:32)
    at Olympus.postDBLoad (/opt/server/user/mods/AssAssIn-Olympus/src/Olympus.ts:56:35)
    at PostDBModLoader.executeModsAsync (/snapshot/src/loaders/PostDBModLoader.ts:77:45)
    at PostDBModLoader.onLoad (/snapshot/src/loaders/PostDBModLoader.ts:30:24)
    at App.load (/snapshot/src/utils/App.ts:57:26)
Error: ENOENT: no such file or directory, scandir 'user/mods/./database/'
Error: ENOENT: no such file or directory, scandir 'user/mods/./database/'
    at Object.readdirSync (node:fs:1515:26)
    at Object.readdirSync (pkg/prelude/bootstrap.js:1306:35)
    at VFS.getFiles (/snapshot/src/utils/VFS.ts:219:19)
    at ImporterUtil.loadRecursive (/snapshot/src/utils/ImporterUtil.ts:87:32)
    at Olympus.postDBLoad (/opt/server/user/mods/AssAssIn-Olympus/src/Olympus.ts:56:35)
    at PostDBModLoader.executeModsAsync (/snapshot/src/loaders/PostDBModLoader.ts:77:45)
    at PostDBModLoader.onLoad (/snapshot/src/loaders/PostDBModLoader.ts:30:24)
    at App.load (/snapshot/src/utils/App.ts:57:26)
```

**Comment by jbs4bmx** [comment]
I'm not very knowledgeable in Docker, but I do believe that you have to pass an argument for it to be able to resolve relative paths.

[Reference 1](https://github.com/docker/cli/pull/3469)

[Reference 2](https://github.com/docker/cli/pull/4966)

**Comment by jbs4bmx** [comment]
Support for Docker is currently under review.
